from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors


def create_pdf_report(
    filename,
    machine_type,
    machine_id,
    manufacturer,
    final_report
):

    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    title_style.textColor = colors.darkblue

    heading_style = styles["Heading2"]
    body_style = styles["BodyText"]

    story = []

    # Title
    story.append(
        Paragraph(
            "MechCare AI",
            title_style
        )
    )

    story.append(
        Paragraph(
            "Machine Maintenance & Troubleshooting Report",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 15))

    # Machine Information
    story.append(
        Paragraph(
            "<b>Machine Information</b>",
            heading_style
        )
    )

    story.append(
        Paragraph(
            f"<b>Machine Type:</b> {machine_type}<br/>"
            f"<b>Machine ID:</b> {machine_id}<br/>"
            f"<b>Manufacturer:</b> {manufacturer}",
            body_style
        )
    )

    story.append(Spacer(1, 20))

    # Final Report
    story.append(
        Paragraph(
            "<b>Engineering Analysis</b>",
            heading_style
        )
    )

    # Convert Markdown-style headings into PDF headings
    for line in final_report.split("\n"):

        line = line.strip()

        if not line:
            story.append(Spacer(1, 6))
            continue

        if line.startswith("## "):

            heading = line.replace("## ", "").strip()

            story.append(
                Paragraph(
                    heading,
                    heading_style
                )
            )

        else:

            line = line.replace("**", "")

            story.append(
                Paragraph(
                    line,
                    body_style
                )
            )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by MechCare AI — AI-Based Mechanical "
            "Maintenance & Troubleshooting Assistant",
            styles["Italic"]
        )
    )

    doc.build(story)
